### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by vitoller** [thp/pyotherside#112]
Hello, 
I am trying to compile a pyotherside project for Android.

My steps:
- Following the guide at docs/index.rst "Building for Android"
- I failed at cloning python3-android: "git clone --branch fixes https://github.com/thp/python3-android"

Is the guide correct? 
Is there another guide / method for building Android Apps?

Thanks

**Comment by thp** [comment]
You have to use a newer Python 3 for Android build, these days it should be
possible to just use normal CPython sources without any patches.

vitoller <notifications@github.com> schrieb am Sa., 15. Feb. 2020, 08:04:

**Comment by ssspeq** [comment]
I am having difficulties making pyotherside for android work. I also followed the instructions "building for android" using this: [https://github.com.cnpmjs.org/yan12125/python3-android](url)

I can not understand why this is happening:

E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libpython3.9.so.1.0" not found
E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:938)
E AndroidRuntime: 	at java.lang.System.load(System.java:1631)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtNative$4.run(QtNative.java:275)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

I would very much appreciate any hits or help on how to solve this. I have been trying to figure it out for a while to the best of my abilities.

**Comment by edips** [comment]
I got the same error as libpython3.9.so.1.0 . I renamed libpython3.9.so to libpython3.9.so.1.0, the result was the same. I tried symlink, it didn't work. I don't know how to manage binary files. Any idea? I think PyOtherSide doesn't clash on Andrpid. I still use gpodder for Android , it works very stable.

**Comment by vitoller** [comment]
If you figure out how to build an app, I would appreciate it if you could write a recipe on how to build it.

Ideal would be a project similar to python-for-android which builds a pyotherside app
