### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by delijati** [thp/pyotherside#86]
I'm running into that error on my 32Bit Aquaris E4.5 Ubuntu Phone (https://github.com/delijati/sparse-qml)

```
qml: Error: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/opt/click.ubuntu.com/sparse-qml.delijati/0.0.1/backend/__init__.py", line 73, in enter_room
    self.active_room.backfill_previous_messages(limit=20)

  File "/opt/click.ubuntu.com/sparse-qml.delijati/0.0.1/lib/py/matrix_client/room.py", line 541, in backfill_previous_messages
    self._put_event(event)

  File "/opt/click.ubuntu.com/sparse-qml.delijati/0.0.1/lib/py/matrix_client/room.py", line 300, in _put_event
    for listener in self.listeners:

OverflowError: Python int too large to convert to C long
```

**Comment by thp** [comment]
Fix pushed to master branch and released as PyOtherSide 1.5.2. Thank you for your bug report!
